# Navigation
nav:
    - Home: index.md
    - Installation:
        - pages/installation/index.md
        - pages/installation/system.md
        - pages/installation/install.md
        - pages/installation/setup.md
    - Konfiguration:
        - Theme:
            - pages/configuration/theme/overview.md
            - pages/configuration/theme/global.md
            - pages/configuration/theme/fonts.md
            - pages/configuration/theme/headings.md
            - pages/configuration/theme/buttons.md
            - pages/configuration/theme/components.md
            - pages/configuration/theme/form.md
            - pages/configuration/theme/modules.md
            - pages/configuration/theme/header.md
            - pages/configuration/theme/miscellaneous.md
            - pages/configuration/theme/layout.md
        - pages/configuration/icon-set.md
        - pages/configuration/backgrounds.md
    - Anleitungen:
          - pages/guides/index.md
          - Demo:
              - Installation:
                  - pages/guides/demo/product-installer.md
                  - pages/guides/demo/contao-manager-theme.md
                  - pages/guides/demo/contao-manager-artefakt.md
          - Skin:
              - pages/guides/skin/introduction.md
              - pages/guides/skin/setup-override.md
          - Konfiguration:
              - pages/guides/configuration/config.md
              - pages/guides/configuration/stylemanager.md

#    - Erweiterung:
#          - pages/extensions/index.md

# Project information
site_url: https://contao-thememanager.github.io/docs/
site_author: co-authored by Daniele Sciannimanica, Sebastian Zoglowek
site_description: >-
    Contao ThemeManager Dokumentation

# Repository
repo_name: contao-thememanager/core
repo_url: https://github.com/contao-thememanager/core

# Edit
edit_uri: https://github.com/contao-thememanager/docs/edit/main/docs

# Copyright
copyright: Copyright &copy; 2024 Oveleon

site_name: Contao ThemeManager
theme:
    name: material
    language: de
    custom_dir: docs/overwrites
    logo: assets/logo.svg
    favicon: assets/logo.svg
    homepage: https://www.contao-thememanager.com
    features:
        - navigation.expand
        - navigation.sections
        - navigation.top
        - navigation.tabs
        - navigation.footer
        - navigation.tracking
        - announce.dismiss
        - content.action.edit
        - content.action.view
        - content.code.annotate
        - content.code.copy
        - search.highlight
        - search.suggest
        - toc.follow
    palette:
        # Palette toggle for automatic mode
        -   media: "(prefers-color-scheme)"
            toggle:
                icon: material/link
                name: Switch to light mode

        # Palette toggle for light mode
        -   media: "(prefers-color-scheme: light)"
            scheme: default
            primary: deep purple
            accent: deep purple
            toggle:
                icon: material/toggle-switch
                name: Switch to dark mode

        # Palette toggle for dark mode
        -   media: "(prefers-color-scheme: dark)"
            scheme: slate
            primary: deep purple
            accent: deep purple
            toggle:
                icon: material/toggle-switch-off-outline
                name: Switch to system preference

plugins:
    - tags
    - glightbox
    - search:
          lang: de

extra:
    generator: false

extra_css:
    - stylesheets/extra.css

markdown_extensions:
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    - md_in_html
    - toc:
          permalink: true
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.emoji:
          emoji_generator: !!python/name:materialx.emoji.to_svg
          emoji_index: !!python/name:materialx.emoji.twemoji
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.keys
    - pymdownx.magiclink:
          repo_url_shorthand: true
          user: squidfunk
          repo: mkdocs-material
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tilde
